name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22'
    - name: Build
      run: go build -o bananenv bananenv.go
    - name: Test
      run: |
        ./bananenv init bash > init.sh
        ./bananenv set FOO=BAR
        ./bananenv list | grep FOO